### ISSUE TITLE
pip3 fails on roboRIO

### ISSUE THREAD

**Issue by virtuald** [robotpy/roborio-packages#2]
This is very strange to me... any thoughts?

```
admin@roboRIO-1418:~# pip3 install -v ipython
Downloading/unpacking ipython
  Could not fetch URL https://pypi.python.org/simple/ipython/: connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
  Will skip URL https://pypi.python.org/simple/ipython/ when looking for download links for ipython
  Could not fetch URL https://pypi.python.org/simple/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/ (Caused by <class 'http.client.CannotSendRequest'>: Request-sent)
  Will skip URL https://pypi.python.org/simple/ when looking for download links for ipython
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not fetch URL https://pypi.python.org/simple/ipython/: connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
  Will skip URL https://pypi.python.org/simple/ipython/ when looking for download links for ipython
  Could not find any downloads that satisfy the requirement ipython
Cleaning up...
  Removing temporary dir /var/volatile/tmp/pip_build_admin...
No distributions at all found for ipython
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python3.4/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/local/lib/python3.4/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
pip.exceptions.DistributionNotFound: No distributions at all found for ipython
```

**Comment by virtuald** [comment]
Never mind, my date is out of sync. Though, this brings up an interesting problem.

**Comment by PeterJohnson** [comment]
The RoboRIO is synchronized to the driver station PC when the DriverStation is connected, but it doesn't have a battery-backed real time clock to keep it in sync when it's turned off.

**Comment by virtuald** [comment]
Ah, didn't know that. Good to know.
